# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options

changelog:
  exclude:
    labels:
      - DO NOT MERGE
      - No Longer Valid
      - Not Reproducible
      - Duplicate
      - Do not publish
