dist: xenial
cache:
  directories:
    - "$HOME/.pip-cache/"
    - ".tox"
os: linux
language: python
python:
  - "3.7"
install:
  - pip install --upgrade pip
  - pip install tox==2.7.0
env:
  matrix:
    - TOX_ENV=python
    - TOX_ENV=generated_sch
script:
  - tox -e $TOX_ENV
