name: CI

on:
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
        poetry-version: ["latest", "1.4.1"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v4.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Print Environment
        run: |
          poetry install
          poetry --version
      - name: Run pytest
        run: poetry run pytest
      - name: Install and Run Pre-Commit
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all-files
