name: CI

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_env: [python, generated_sch]
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      -
        name: Set up Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          # NOTE: Poetry won't be in PATH until following steps
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
          $HOME/.poetry/bin/poetry install
      -
        name: Print Environment
        run: poetry --version
      -
        name: Tox ${{ matrix.test_env }}
        run: poetry run tox -e ${{ matrix.test_env }}
